# ERB still processes things in YAML comments.
# Putting this in a comment makes editor syntax highlighting happier.
# <% require_relative "./lib/engine_list" %>

# Name of your application. Used to uniquely configure containers.
service: toybox

# Name of the container image.
image: kylecoding/toybox

retain_containers: 2

# Deploy to these servers.
servers:
  web:
    - 165.227.64.16

proxy:
  ssl: true
  hosts:
    - toybox.kylecoding.com
    # <% Toybox::ENGINE_LIST.each do |engine_name| %>
    - <%= engine_name.dasherize %>.toybox.kylecoding.com
    # <% end %>

registry:
  # Use a local docker registry to save on costs.
  # This setup is intended for single-server deploys.
  server: localhost:5555

env:
  secret:
    - SECRET_KEY_BASE
    - TOYBOX_DATABASE_PASSWORD
    - TOYBOX_DATABASE_HOST
    - TOYBOX_DATABASE_PORT
  clear: {}

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

# Use a persistent storage volume for local Active Storage files.
# Recommended to change this to a mounted volume path that is backed up off server.
volumes:
  - "toybox_storage:/rails/storage"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /rails/public/assets

# Configure the image builder.
builder:
  arch: amd64
  args:
    RUBY_VERSION: <%= File.read(".ruby-version").chomp %>

  # # Build image via remote server (useful for faster amd64 builds on arm64 computers)
  # remote: ssh://docker@docker-builder-server
  #
  # # Pass arguments and secrets to the Docker build process
  # args:
  #   RUBY_VERSION: 3.4.2
  # secrets:
  #   - GITHUB_TOKEN
  #   - RAILS_MASTER_KEY

# Use a different ssh user than root
# ssh:
#   user: app

accessories:
  # Valkey accessory for Action Cable
  valkey:
    image: valkey/valkey:9.0.1-alpine
    host: 165.227.64.16
    port: "127.0.0.1:6379:6379"
